### ISSUE TITLE
Remove all mycs occurrences

### ISSUE THREAD

**Issue by NicolasRitouet** [mycsHQ/ns-suitescript-mocks#5]
Since this library is not used exclusively by `mycs` anymore, we should remove all occurrences of mycs in the codebase.
https://github.com/mycsHQ/ns-suitescript-mocks/search?q=mycs&type=Code

**Comment by chaverri** [comment]
Hey, 

I started just today creating my own mock library, and I started to check for someone similar till I found this. 

This is awesome, if I can help in any way please just let me know.
